services:
  # Elasticsearch: основной сервис для поиска продуктов
  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.12.0'
    container_name: elasticsearch
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - '9226:9200'
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 10s
      timeout: 5s
      retries: 5

  # База данных Postgres
  postgres:
    image: 'postgres:latest'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=recommendation_db'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=user'
    # Добавляем команду для увеличения лимита подключений до 200
    command: [ "postgres", "-c", "max_connections=200" ]
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d recommendation_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Кэш Redis
  redis:
    image: 'redis:latest'
    container_name: redis
    ports:
      - '6380:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Инфраструктура Kafka
  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.5.0'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: 'confluentinc/cp-kafka:7.5.0'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9098:9098'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9098
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Ваше Java-приложение
  recommendation-service:
    build: .
    container_name: recommendation-service
    ports:
      - "8026:8026"
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      # Внутри Docker переопределяем URL, чтобы приложение шло по имени сервиса
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/recommendation_db
      - SPRING_DATA_REDIS_HOST=redis