spring.application.name=Recommendation-Service
server.port=8026

# БД Postgres - используем имя сервиса и ВНУТРЕННИЙ порт
spring.datasource.url=jdbc:postgresql://localhost:5433/recommendation_db
spring.datasource.username=user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

# Elasticsearch - используем переменную или localhost
spring.elasticsearch.uris=${ELASTICSEARCH_URL:http://localhost:9226}

# Redis - для локального запуска используйте localhost:6380
spring.data.redis.host=localhost
spring.data.redis.port=6380

# Kafka - используем имя сервиса и ВНУТРЕННИЙ порт
# Замените kafka:9092 на localhost:9098 для локального запуска
spring.kafka.bootstrap-servers=localhost:9098
spring.kafka.consumer.group-id=rec-group

# Отключаем лишние логи на время теста
logging.level.com.example.recommendationservice=WARN
logging.level.org.springframework=WARN

# Увеличиваем количество потоков сервера
server.tomcat.threads.max=1000
server.tomcat.max-connections=20000
# Увеличиваем пул соединений к БД
spring.datasource.hikari.maximum-pool-size=10

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.jpa.open-in-view=false
# Открываем эндпоинты для доступа
management.endpoints.web.exposure.include=health,info,metrics
# Позволяет видеть детальный статус (DB, Kafka, Redis)
management.endpoint.health.show-details=always