spring.application.name=Recommendation-Service
server.port=8026

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/recommendation_db}
spring.datasource.username=user
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=update

spring.elasticsearch.uris=${ELASTICSEARCH_URL:http://elasticsearch:9200}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=rec-group

logging.level.com.example.recommendationservice=WARN
logging.level.org.springframework=WARN

server.tomcat.threads.max=1000
server.tomcat.max-connections=20000
spring.datasource.hikari.maximum-pool-size=20

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true

spring.jpa.open-in-view=false
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always